
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 25 14:35:19 BRT 2020
//----------------------------------------------------

package src.sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 14;
  public static final int SYMBOL_ASSIGNMENT = 23;
  public static final int FUNCTION_PARAMS = 16;
  public static final int END = 4;
  public static final int CALL_FUNCTION = 9;
  public static final int FF = 20;
  public static final int LEFT_BRACKETS = 17;
  public static final int FUNCTION = 15;
  public static final int VARIABLE = 5;
  public static final int IF = 21;
  public static final int COLON = 6;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int STRING = 13;
  public static final int STRING_TYPE = 8;
  public static final int INTEGER_TYPE = 7;
  public static final int EOF = 0;
  public static final int RIGHT_BRACKETS = 18;
  public static final int RIGHT_PARAMETER = 10;
  public static final int LEFT_PARAMETER = 11;
  public static final int error = 1;
  public static final int TT = 19;
  public static final int ASSIGNMENT = 22;
  public static final int INTEGER = 12;
}

